name: dev_frontend_skytrade_build_deploy 

on:
  push:
    branches: [ "dev-deploy" ]

jobs:
  build:
    runs-on: skytrade-dev

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: bash ./dev_env.sh
    - run: pm2 stop ecosystem.config.js --env dev
    - run: npm i && npm run build
    - run: pm2 startOrRestart ecosystem.config.js --env dev